name: "Style check"
description: "Check code style using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      run: |
        PROJECT_PATH=$(pwd)

        SOURCE_FILES=$(find $PROJECT_PATH/src $PROJECT_PATH/include -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" -o -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt
        clang-format -n $SOURCE_FILES 2> ${ERROR_FILE_FLAG}

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: Some files are not formatted correctly"
            cat $ERROR_FILE_FLAG
            exit 1
        else
            echo "All files are formatted correctly."
        fi
      shell: bash  # Add this line
