name: "Build Project"
description: "Build project using Conan and CMake"

runs:
  using: "composite"
  steps:
    - name: Install Python and pip
      run: sudo apt-get update && sudo apt-get install -y python3-pip python3-venv
      shell: bash

    - name: Setup Python venv
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install conan
      shell: bash

    - name: Conan install
      run: |
        source .venv/bin/activate
        mkdir -p build
        cd build
        conan profile detect --force
        conan install .. --build=missing
      shell: bash

    - name: Install build tools
      run: sudo apt-get install -y cmake build-essential libreadline-dev
      shell: bash

    - name: Configure and Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
      shell: bash
