name: "Documentation Check"
description: "Generates and validates code documentation using Doxygen"

runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3

    - name: "Install Dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
      shell: bash

    - name: "Run Doxygen Command"
      shell: bash
      run: |
        # Define the path to the Doxyfile
        DOX_CONF_FILE=$(pwd)/Doxyfile

        # Verify that Doxyfile exists
        if [ ! -f "$DOX_CONF_FILE" ]; then
          echo "Error: Doxyfile not found at $DOX_CONF_FILE"
          exit 1
        fi

        # Backup the original Doxyfile
        cp $DOX_CONF_FILE ${DOX_CONF_FILE}.bak

        # Append input directories to the Doxyfile
        {
          grep -v "^INPUT\s*=" ${DOX_CONF_FILE}.bak
          echo "INPUT = $(pwd)/src $(pwd)/include"
        } > $DOX_CONF_FILE

        # Clear Graphviz configuration if necessary
        sudo dot -c

        # Define the error file path
        ERROR_FILE_FLAG=$(pwd)/dox_errors.txt

        # Run Doxygen and capture errors
        doxygen $DOX_CONF_FILE 2> $ERROR_FILE_FLAG

        # Check if the error file is non-empty
        if [ -s $ERROR_FILE_FLAG ]; then
          echo "Error: There are some documentation issues."
          cat $ERROR_FILE_FLAG
          exit 1
        else
          echo "All documentation generated correctly."
          exit 0
        fi

    - name: "Upload Doxygen Errors"
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Doxygen-Errors
        path: ./dox_errors.txt
        retention-days: 1
